"use client";

import { FormEvent, useState } from "react";

type Screen = "welcome" | "login" | "onboarding" | "home" | "mypage";
type Farm = { name: string; phone: string; region: string; location: string; category: string; crop: string; scale: string; facility: string };
const initialFarm: Farm = { name: "김농부", phone: "010-1234-5678", region: "충청북도 청주시", location: "청주시 상당구 미원면", category: "농작물", crop: "사과", scale: "3,000평", facility: "과수원 · 저온저장고" };
const steps = [
  { key: "name", title: "성함을 알려주세요", hint: "서비스에서 부를 이름이에요.", placeholder: "예: 김농부" },
  { key: "phone", title: "연락처를 입력해 주세요", hint: "지원 신청기한 안내에 사용해요.", placeholder: "010-0000-0000" },
  { key: "region", title: "어디에 거주하시나요?", hint: "시·도와 시·군·구를 알려주세요.", placeholder: "예: 충청북도 청주시" },
  { key: "location", title: "농지는 어디에 있나요?", hint: "정확한 주소를 몰라도 읍·면·동까지만 괜찮아요.", placeholder: "예: 청주시 상당구 미원면" },
  { key: "category", title: "어떤 농업을 하고 계세요?", hint: "가장 가까운 항목을 선택하세요.", options: ["농작물", "축산", "농업시설", "복합 농가"] },
  { key: "crop", title: "주요 작목이나 축종은 무엇인가요?", hint: "여러 가지라면 대표 하나만 입력해도 괜찮아요.", placeholder: "예: 사과, 벼, 한우" },
  { key: "scale", title: "농가 규모를 알려주세요", hint: "정확하지 않아도 대략적인 규모면 충분해요.", placeholder: "예: 3,000평 또는 한우 25마리" },
  { key: "facility", title: "보유한 농업시설이 있나요?", hint: "없다면 ‘없음’이라고 입력해 주세요.", placeholder: "예: 비닐하우스 2동, 저온저장고" },
] as const;

export default function App() {
  const [screen, setScreen] = useState<Screen>("welcome"); const [step, setStep] = useState(0);
  const [farm, setFarm] = useState<Farm>(initialFarm); const [draft, setDraft] = useState<Farm>(initialFarm); const [editing, setEditing] = useState(false);
  const goHome = () => { setScreen("home"); window.scrollTo(0, 0); };
  const startOnboarding = () => { setFarm({ name:"", phone:"", region:"", location:"", category:"", crop:"", scale:"", facility:"" }); setStep(0); setScreen("onboarding"); };
  const nextStep = () => step < steps.length - 1 ? setStep(step + 1) : goHome();
  if (screen === "welcome") return <Welcome onStart={startOnboarding} onLogin={() => setScreen("login")} />;
  if (screen === "login") return <Login onBack={() => setScreen("welcome")} onLogin={goHome} />;
  if (screen === "onboarding") { const item = steps[step]; const value = farm[item.key]; return <main className="onboarding-shell"><header className="simple-header"><Logo /><button className="text-button" onClick={() => setScreen("welcome")}>나가기</button></header><div className="progress-wrap"><div className="progress-meta"><span>농가 정보 등록</span><b>{step + 1} / {steps.length}</b></div><div className="progress"><i style={{width:`${(step + 1) / steps.length * 100}%`}} /></div></div><section className="question-card"><p className="question-number">질문 {step + 1}</p><h1>{item.title}</h1><p className="question-hint">{item.hint}</p>{"options" in item ? <div className="option-grid">{item.options.map(option => <button key={option} className={`choice ${value === option ? "selected" : ""}`} onClick={() => setFarm({...farm,[item.key]:option})}>{value === option ? "✓ " : ""}{option}</button>)}</div> : <label className="sr-label">{item.title}<input autoFocus value={value} onChange={e => setFarm({...farm,[item.key]:e.target.value})} placeholder={item.placeholder} /></label>}<div className="onboarding-actions"><button className="secondary" disabled={step === 0} onClick={() => setStep(step - 1)}>이전</button><button className="primary" disabled={!value.trim()} onClick={nextStep}>{step === steps.length - 1 ? "등록 완료" : "다음"}</button></div><button className="skip" onClick={nextStep}>잘 모르겠어요 · 나중에 입력</button></section></main>; }
  if (screen === "mypage") return <MyPage farm={farm} draft={draft} editing={editing} setEditing={v => { setEditing(v); setDraft(farm); }} setDraft={setDraft} onSave={() => {setFarm(draft);setEditing(false);}} onHome={goHome} />;
  return <Dashboard farm={farm} onMyPage={() => setScreen("mypage")} />;
}

function Logo() { return <div className="logo compact"><span className="brand-mark">온</span><strong>농가온</strong></div>; }
function Welcome({onStart,onLogin}:{onStart:()=>void;onLogin:()=>void}) { return <main className="welcome"><section className="welcome-copy"><Logo /><div><p className="eyebrow">농가의 일상과 회복을 함께</p><h1>피해 현장에서<br/><em>막막하지 않도록</em></h1><p className="lead">사진을 찍고 말로 설명하면, 피해 기록부터 복구지원 준비까지 차근차근 도와드려요.</p><div className="actions"><button className="primary" onClick={onStart}>처음 시작하기</button><button className="secondary" onClick={onLogin}>이미 가입했어요</button></div><p className="trust">✓ 입력한 정보는 안전하게 보호됩니다</p></div></section><section className="welcome-art" aria-label="농가 피해 기록 서비스 안내"><div className="sun"/><div className="field field-one"/><div className="field field-two"/><div className="phone"><div className="phone-top"/><div className="photo-placeholder">▧</div><div className="voice-line">● &nbsp; 말씀해 주세요</div></div><div className="floating-card card-one"><b>① 현장 기록</b><span>사진과 음성으로 간단하게</span></div><div className="floating-card card-two"><b>② 맞춤 안내</b><span>내 피해에 맞는 지원 확인</span></div></section></main>; }
function Login({onBack,onLogin}:{onBack:()=>void;onLogin:()=>void}) { const [sent,setSent]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault(); sent ? onLogin() : setSent(true)}; return <main className="shell centered"><button className="back" onClick={onBack}>← 돌아가기</button><form className="auth-card" onSubmit={submit}><div className="brand-mark">온</div><p className="eyebrow">다시 만나 반가워요</p><h1>로그인</h1><label>휴대전화 번호<input required inputMode="tel" defaultValue="010-1234-5678" placeholder="010-0000-0000"/></label>{sent && <label>인증번호<input required inputMode="numeric" defaultValue="123456" placeholder="숫자 6자리"/></label>}<button className="primary">{sent ? "로그인하기" : "인증번호 받기"}</button><p className="demo-note">데모 화면입니다. 실제 인증은 진행되지 않습니다.</p></form></main>; }
function Dashboard({farm,onMyPage}:{farm:Farm;onMyPage:()=>void}) { return <main className="app-shell"><header className="app-header"><Logo/><nav><button className="nav-active">홈</button><button>피해 기록</button><button>신청 준비</button><button onClick={onMyPage}>내 농가</button></nav><button className="profile-button" onClick={onMyPage}><span>김</span>{farm.name || "김농부"} 님</button></header><section className="dashboard"><div className="greeting"><div><p className="eyebrow">2026년 8월 16일 일요일</p><h1>{farm.name || "농부"}님,<br/>오늘 농가는 괜찮으신가요?</h1><p>피해가 생겼다면 현장에서 바로 기록해 두세요.<br/>필요한 지원과 준비할 일을 함께 찾아드릴게요.</p></div><div className="weather-card"><span className="weather-icon">☀</span><div><b>{farm.region || "충청북도 청주시"}</b><strong>29°</strong><small>폭염주의보 · 야외 활동에 유의하세요</small></div></div></div><button className="hero-action"><span className="camera-icon">▣</span><span><small>새로운 피해가 생겼나요?</small><b>피해 현장 기록 시작하기</b><em>사진과 음성으로 3분이면 충분해요</em></span><i>→</i></button><section className="home-grid"><article className="panel"><div className="panel-title"><div><span className="mini-icon">⌁</span><h2>진행 중인 피해 기록</h2></div><button>전체 보기 →</button></div><div className="empty-state"><span>✓</span><b>현재 진행 중인 피해 기록이 없어요</b><p>농가가 무사하다니 다행이에요.</p></div></article><article className="panel quick"><div className="panel-title"><div><span className="mini-icon">☷</span><h2>빠른 메뉴</h2></div></div><button onClick={onMyPage}><span>▧</span><div><b>내 농가 정보</b><small>{farm.crop || "사과"} · {farm.scale || "3,000평"}</small></div><i>›</i></button><button><span>♡</span><div><b>관심 지원사업</b><small>저장된 지원 0건</small></div><i>›</i></button></article></section></section><BottomNav onMyPage={onMyPage}/></main>; }
function BottomNav({onMyPage}:{onMyPage:()=>void}) { return <nav className="bottom-nav"><button className="active">⌂<span>홈</span></button><button>▧<span>피해 기록</span></button><button>☷<span>신청 준비</span></button><button onClick={onMyPage}>●<span>내 농가</span></button></nav>; }
function MyPage({farm,draft,editing,setEditing,setDraft,onSave,onHome}:{farm:Farm;draft:Farm;editing:boolean;setEditing:(v:boolean)=>void;setDraft:(v:Farm)=>void;onSave:()=>void;onHome:()=>void}) { const fields:[keyof Farm,string][]=[["name","이름"],["phone","휴대전화"],["region","거주 지역"],["location","농지 위치"],["category","농업 유형"],["crop","주요 작목·축종"],["scale","농가 규모"],["facility","보유 시설"]]; return <main className="app-shell"><header className="app-header"><Logo/><button className="text-button" onClick={onHome}>홈으로</button></header><section className="mypage"><div className="page-heading"><div><p className="eyebrow">내 농가</p><h1>농가 정보 관리</h1><p>피해지원 안내에 반복해서 사용하는 정보예요.</p></div>{!editing && <button className="secondary" onClick={()=>setEditing(true)}>정보 수정하기</button>}</div><article className="profile-summary"><div className="avatar">김</div><div><h2>{farm.name || "김농부"} 님</h2><p>{farm.region || "지역 미입력"} · {farm.crop || "작목 미입력"}</p></div><span className="status">✓ 등록 완료</span></article><section className="info-card"><div className="info-title"><h2>기본 정보</h2><span>마지막 수정: 오늘</span></div><div className="info-grid">{fields.map(([key,label])=><label key={key}><span>{label}</span>{editing?<input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<b>{farm[key] || "입력되지 않음"}</b>}</label>)}</div>{editing&&<div className="edit-actions"><button className="secondary" onClick={()=>setEditing(false)}>취소</button><button className="primary" onClick={onSave}>저장하기</button></div>}</section><button className="logout" onClick={onHome}>로그아웃</button></section><BottomNav onMyPage={()=>{}}/></main>; }
