"use client";

import { ChangeEvent, FormEvent, useRef, useState } from "react";
import type { ReactNode } from "react";

type Screen = "welcome" | "login" | "onboarding" | "home" | "mypage" | "damage" | "cases";
type Farm = { name:string; phone:string; region:string; location:string; farmName:string; livestockType:string; normalCount:string; barnCount:string; barnArea:string; ownership:string; permitNumber:string; businessRegistered:string; insuranceEnrolled:string; insurer:string; contractNumber:string };
const emptyFarm: Farm = { name:"",phone:"",region:"",location:"",farmName:"",livestockType:"",normalCount:"",barnCount:"",barnArea:"",ownership:"",permitNumber:"",businessRegistered:"",insuranceEnrolled:"",insurer:"",contractNumber:"" };
const initialFarm: Farm = { name:"김한우",phone:"010-1234-5678",region:"충청북도 청주시",location:"청주시 상당구 미원면",farmName:"미원한우농장",livestockType:"한우",normalCount:"45두",barnCount:"2동",barnArea:"1,200㎡",ownership:"소유",permitNumber:"축산업-청주-2021-0182",businessRegistered:"등록",insuranceEnrolled:"가입",insurer:"NH농협손해보험",contractNumber:"LIV-2026-004521" };
const steps = [
  { key: "name", title: "성함을 알려주세요", hint: "서비스에서 부를 이름이에요.", placeholder: "예: 김농부" },
  { key: "phone", title: "연락처를 입력해 주세요", hint: "지원 신청기한 안내에 사용해요.", placeholder: "010-0000-0000" },
  { key: "region", title: "어디에 거주하시나요?", hint: "시·도와 시·군·구를 알려주세요.", placeholder: "예: 충청북도 청주시" },
  { key: "farmName", title: "농장 이름을 알려주세요", hint: "등록된 농장명 또는 평소 부르는 이름이에요.", placeholder: "예: 미원한우농장" },
  { key: "location", title: "축산 농장은 어디에 있나요?", hint: "정확한 주소를 몰라도 읍·면·동까지만 괜찮아요.", placeholder: "예: 청주시 상당구 미원면" },
  { key: "livestockType", title: "어떤 가축을 기르고 계세요?", hint: "주요 축종을 선택해 주세요.", options: ["한우", "젖소", "돼지", "닭", "오리", "기타"] },
  { key: "normalCount", title: "평소 사육두수는 몇 마리인가요?", hint: "피해 마릿수와 비교할 때 필요한 정보예요.", placeholder: "예: 한우 45두" },
  { key: "barnCount", title: "축사는 몇 동인가요?", hint: "현재 운영하는 전체 축사 수를 알려주세요.", placeholder: "예: 2동" },
  { key: "insuranceEnrolled", title: "가축재해보험에 가입했나요?", hint: "보험 사고접수 안내에 활용해요.", options: ["가입", "미가입", "잘 모르겠음"] },
] as const;

export default function App() {
  const [screen, setScreen] = useState<Screen>("welcome"); const [step, setStep] = useState(0);
  const [farm, setFarm] = useState<Farm>(initialFarm); const [draft, setDraft] = useState<Farm>(initialFarm); const [editing, setEditing] = useState(false);
  const goHome = () => { setScreen("home"); window.scrollTo(0, 0); };
  const startOnboarding = () => { setFarm(emptyFarm); setStep(0); setScreen("onboarding"); };
  const nextStep = () => step < steps.length - 1 ? setStep(step + 1) : goHome();
  if (screen === "welcome") return <Welcome onStart={startOnboarding} onLogin={() => setScreen("login")} />;
  if (screen === "login") return <Login onBack={() => setScreen("welcome")} onLogin={goHome} />;
  if (screen === "onboarding") { const item = steps[step]; const value = farm[item.key]; return <main className="onboarding-shell"><header className="simple-header"><Logo onHome={goHome}/><button className="text-button" onClick={() => setScreen("welcome")}>나가기</button></header><div className="progress-wrap"><div className="progress-meta"><span>농가 정보 등록</span><b>{step + 1} / {steps.length}</b></div><div className="progress"><i style={{width:`${(step + 1) / steps.length * 100}%`}} /></div></div><section className="question-card"><p className="question-number">질문 {step + 1}</p><h1>{item.title}</h1><p className="question-hint">{item.hint}</p>{"options" in item ? <div className="option-grid">{item.options.map(option => <button key={option} className={`choice ${value === option ? "selected" : ""}`} onClick={() => setFarm({...farm,[item.key]:option})}>{value === option ? "✓ " : ""}{option}</button>)}</div> : <label className="sr-label">{item.title}<input autoFocus value={value} onChange={e => setFarm({...farm,[item.key]:e.target.value})} placeholder={item.placeholder} /></label>}<div className="onboarding-actions"><button className="secondary" disabled={step === 0} onClick={() => setStep(step - 1)}>이전</button><button className="primary" disabled={!value.trim()} onClick={nextStep}>{step === steps.length - 1 ? "등록 완료" : "다음"}</button></div><button className="skip" onClick={nextStep}>잘 모르겠어요 · 나중에 입력</button></section></main>; }
  if (screen === "damage") return <DamageFlow farm={farm} onHome={goHome} />;
  if (screen === "cases") return <DamageCases farm={farm} onHome={goHome} onStartRecord={() => setScreen("damage")} />;
  if (screen === "mypage") return <MyPage farm={farm} draft={draft} editing={editing} setEditing={v => { setEditing(v); setDraft(farm); }} setDraft={setDraft} onSave={() => {setFarm(draft);setEditing(false);}} onHome={goHome} />;
  return <Dashboard farm={farm} onHome={goHome} onMyPage={() => setScreen("mypage")} onDamage={() => setScreen("damage")} onCases={() => setScreen("cases")} />;
}

function Logo({onHome}:{onHome?:()=>void}) { const content=<><span className="brand-mark">온</span><strong>농가온</strong></>; return onHome?<button className="logo compact logo-button" onClick={onHome} aria-label="농가온 홈으로 이동">{content}</button>:<div className="logo compact">{content}</div>; }
function Welcome({onStart,onLogin}:{onStart:()=>void;onLogin:()=>void}) { return <main className="welcome"><section className="welcome-copy"><Logo /><div><p className="eyebrow">축산농가의 안전과 회복을 함께</p><h1>가축과 축사 피해,<br/><em>막막하지 않도록</em></h1><p className="lead">현장 사진을 찍고 말로 설명하면, 축산 피해 기록부터 복구지원과 문서 준비까지 차근차근 도와드려요.</p><div className="actions"><button className="primary" onClick={onStart}>축산농가 등록하기</button><button className="secondary" onClick={onLogin}>이미 가입했어요</button></div><p className="trust">✓ 입력한 농장정보는 안전하게 보호됩니다</p></div></section><section className="welcome-art" aria-label="축산농가 피해 기록 서비스 안내"><div className="sun"/><div className="field field-one"/><div className="field field-two"/><div className="phone"><div className="phone-top"/><div className="photo-placeholder">♉</div><div className="voice-line">● &nbsp; 피해를 말씀해 주세요</div></div><div className="floating-card card-one"><b>① 축산 피해 기록</b><span>사진과 음성으로 간단하게</span></div><div className="floating-card card-two"><b>② 복구지원 안내</b><span>지역·축종·피해에 맞게 확인</span></div></section></main>; }
function Login({onBack,onLogin}:{onBack:()=>void;onLogin:()=>void}) { const [sent,setSent]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault(); sent ? onLogin() : setSent(true)}; return <main className="shell centered"><button className="back" onClick={onBack}>← 돌아가기</button><form className="auth-card" onSubmit={submit}><div className="brand-mark">온</div><p className="eyebrow">다시 만나 반가워요</p><h1>로그인</h1><label>휴대전화 번호<input required inputMode="tel" defaultValue="010-1234-5678" placeholder="010-0000-0000"/></label>{sent && <label>인증번호<input required inputMode="numeric" defaultValue="123456" placeholder="숫자 6자리"/></label>}<button className="primary">{sent ? "로그인하기" : "인증번호 받기"}</button><p className="demo-note">데모 화면입니다. 실제 인증은 진행되지 않습니다.</p></form></main>; }
function Dashboard({farm,onHome,onMyPage,onDamage,onCases}:{farm:Farm;onHome:()=>void;onMyPage:()=>void;onDamage:()=>void;onCases:()=>void}) { return <main className="app-shell"><header className="app-header"><Logo onHome={onHome}/><nav><button className="nav-active" onClick={onHome}>홈</button><button onClick={onCases}>축산 피해 기록</button><button>신고·신청 준비</button><button onClick={onMyPage}>내 농장</button></nav><button className="profile-button" onClick={onMyPage}><span>김</span>{farm.name || "김한우"} 님</button></header><section className="dashboard"><div className="greeting"><div><p className="eyebrow">2026년 8월 16일 일요일</p><h1>{farm.name || "농장주"}님,<br/>오늘 가축과 축사는 안전한가요?</h1><p>피해가 생겼다면 현장에서 바로 기록해 두세요.<br/>확인할 복구지원과 준비할 문서를 함께 정리해드릴게요.</p></div><div className="weather-card"><span className="weather-icon">☀</span><div><b>{farm.region || "충청북도 청주시"}</b><strong>29°</strong><small>폭염주의보 · 가축 음수와 축사 환기를 확인하세요</small></div></div></div><button className="hero-action" onClick={onDamage}><span className="camera-icon">▣</span><span><small>가축이나 축사에 피해가 생겼나요?</small><b>축산 피해 현장 기록 시작하기</b><em>사진과 음성으로 3분이면 충분해요</em></span><i>→</i></button><section className="home-grid"><article className="panel"><div className="panel-title"><div><span className="mini-icon">⌁</span><h2>진행 중인 축산 피해 기록</h2></div><button onClick={onCases}>전체 보기 →</button></div><button className="home-record" onClick={onCases}><span className="home-record-status">진행 중</span><div><b>집중호우 · 축사 침수</b><small>한우 {farm.normalCount || "45두"} 중 폐사 신고 2두 · 축사 {farm.barnCount || "2동"} 중 1동 침수</small><em>사진 3장 · 관련 지원 3건</em></div><i>›</i></button></article><article className="panel quick"><div className="panel-title"><div><span className="mini-icon">☷</span><h2>내 축산농가</h2></div></div><button onClick={onMyPage}><span>♉</span><div><b>{farm.farmName || "미원한우농장"}</b><small>{farm.livestockType || "한우"} {farm.normalCount || "45두"} · 축사 {farm.barnCount || "2동"}</small></div><i>›</i></button><button><span>▣</span><div><b>가축재해보험</b><small>{farm.insuranceEnrolled || "가입 여부 미확인"} · {farm.insurer || "보험사 미입력"}</small></div><i>›</i></button></article></section></section><BottomNav onMyPage={onMyPage} onCases={onCases}/></main>; }
function BottomNav({onMyPage,onCases}:{onMyPage:()=>void;onCases?:()=>void}) { return <nav className="bottom-nav"><button className="active">⌂<span>홈</span></button><button onClick={onCases}>▧<span>축산 피해</span></button><button>☷<span>신고 준비</span></button><button onClick={onMyPage}>●<span>내 농장</span></button></nav>; }

function DamageCases({farm,onHome,onStartRecord}:{farm:Farm;onHome:()=>void;onStartRecord:()=>void}) { const [open,setOpen]=useState<"damage"|"support"|null>(null); const supports=[{state:"적용 가능성 있음",title:"자연재난 축산 피해 신고",body:"집중호우로 인한 한우 폐사와 축사 침수 피해가 기록되어 있어요.",action:"읍·면·동 행정복지센터에 신고기한 확인"},{state:"추가 확인 필요",title:"축사·축산시설 복구지원",body:"축사 벽체와 사료 저장시설 파손 기록을 바탕으로 확인해 볼 수 있어요.",action:"시설 사진과 소유·임차 자료 확인"},{state:"추가 확인 필요",title:"가축재해보험 사고접수",body:`${farm.insurer || "보험사"} 가입 정보가 있어 폐사 신고와 함께 확인해 볼 수 있어요.`,action:"보험 계약번호와 사고 접수 가능 여부 확인"}]; return <main className="app-shell"><header className="app-header"><Logo onHome={onHome}/><button className="text-button" onClick={onHome}>홈으로</button></header><section className="damage-cases"><div className="cases-heading"><div><p className="eyebrow">축산 피해</p><h1>피해 기록과<br/>관련 지원을 확인하세요</h1><p>사진과 말씀으로 남긴 기록을 바탕으로 신고·복구지원·보험 경로를 정리했어요.</p></div><button className="primary" onClick={onStartRecord}>＋ 새 축산 피해 기록하기</button></div><article className="damage-case-card"><div className="case-top"><span>진행 중</span><small>2026년 8월 16일 새벽 · {farm.location || "청주시 상당구 미원면"}</small></div><h2>집중호우 · 축사 침수</h2><p className="case-summary">{farm.livestockType || "한우"} {farm.normalCount || "45두"} 중 폐사 신고 2두 · 축사 {farm.barnCount || "2동"} 중 1동 침수 · 사료 저장시설 파손</p><div className="case-evidence"><span>▣ 사진 3장</span><span>● 음성 설명 1건</span></div><div className="case-actions"><button className="secondary" onClick={()=>setOpen(open==="damage"?null:"damage")}>피해 내용 확인</button><button className="primary" onClick={()=>setOpen(open==="support"?null:"support")}>관련 지원 3건 보기</button></div>{open==="damage"&&<div className="case-detail"><h3>피해 내용 확인</h3><div><span>발생일시</span><b>2026년 8월 16일 새벽 3시경</b><em>사용자 확인</em></div><div><span>피해 원인</span><b>집중호우로 인한 침수</b><em>사용자 설명</em></div><div><span>가축 피해</span><b>{farm.livestockType || "한우"} {farm.normalCount || "45두"} 중 폐사 신고 2두</b><em>사용자 확인</em></div><div><span>시설 피해</span><b>축사 벽체 · 사료 저장시설</b><em className="needs-check">추가 확인 필요</em></div><p className="ai-notice">AI가 정리한 내용은 공식 피해 판정이 아닙니다. 신고와 지원 확인을 돕기 위한 자료입니다.</p></div>}{open==="support"&&<div className="support-list">{supports.map(item=><article key={item.title}><span>{item.state}</span><h3>{item.title}</h3><p>{item.body}</p><b>가장 먼저: {item.action}</b><button>상세 조건 보기 →</button></article>)}</div>}</article></section><BottomNav onMyPage={onHome} onCases={()=>{}}/></main>; }

type DamageStage = "safety" | "capture" | "review" | "callStart" | "call" | "summary" | "structure" | "support" | "documents";
type Photo = { id:number; url:string; name:string; note:string; time:string };
const questions = [
  "어떤 피해가 있었나요? 평소 말하듯 천천히 말씀해 주세요.",
  "피해는 언제 발생했나요? 정확하지 않아도 괜찮습니다.",
  "피해를 입은 가축과 축사 시설은 무엇인가요?",
  "평소 한우 45두를 사육하신 것으로 확인됩니다. 폐사하거나 다친 가축이 몇 두인지 알려주시겠어요?",
  "침수된 축사와 지금 가장 필요한 긴급 복구는 무엇인가요?",
];
const sampleAnswers = ["어젯밤 비가 많이 와서 아래쪽 축사가 물에 잠겼어요.","8월 16일 새벽 3시쯤 발생했습니다.","한우와 아래쪽 축사, 사료 저장시설이 피해를 입었어요.","한우 45두 중 2두가 폐사했고 다친 소는 아직 확인 중입니다.","축사 2동 중 1동이 침수됐고 배수와 벽체, 사료시설 복구가 필요해요."];

function DamageFlow({farm,onHome}:{farm:Farm;onHome:()=>void}) {
  const [stage,setStage]=useState<DamageStage>("safety"); const [photos,setPhotos]=useState<Photo[]>([]); const [question,setQuestion]=useState(0); const [messages,setMessages]=useState<{who:"ai"|"user";text:string}[]>([]); const [answer,setAnswer]=useState(""); const [listening,setListening]=useState(false); const fileRef=useRef<HTMLInputElement>(null); const cameraRef=useRef<HTMLInputElement>(null);
  const speak=(text:string)=>{ if (!("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const utter=new SpeechSynthesisUtterance(text); utter.lang="ko-KR"; utter.rate=.78; utter.pitch=1; utter.volume=1; const voices=window.speechSynthesis.getVoices(); const korean=voices.find(v=>v.lang.toLowerCase().startsWith("ko")); if(korean) utter.voice=korean; window.speechSynthesis.speak(utter); };
  const addPhotos=(e:ChangeEvent<HTMLInputElement>)=>{ const files=Array.from(e.target.files||[]); const now=new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}); setPhotos(prev=>[...prev,...files.map((f,i)=>({id:Date.now()+i,url:URL.createObjectURL(f),name:f.name,note:"",time:now}))]); setStage("review"); e.target.value=""; };
  const beginCall=()=>{ const first={who:"ai" as const,text:questions[0]}; setMessages([first]); setStage("call"); speak(first.text); };
  const send=(text=answer)=>{ const clean=text.trim(); if(!clean)return; const next=question+1; const updated=[...messages,{who:"user" as const,text:clean}]; if(next<questions.length){ updated.push({who:"ai",text:questions[next]}); setQuestion(next); setMessages(updated); setAnswer(""); speak(questions[next]); } else { setMessages(updated); setAnswer(""); setStage("summary"); speak("말씀해 주신 내용을 정리했습니다. 화면의 내용이 맞는지 천천히 확인해 주세요."); } };
  const listen=()=>{ const w=window as unknown as {webkitSpeechRecognition?:new()=>{lang:string;interimResults:boolean;onresult:(e:{results:{0:{0:{transcript:string}}}[]})=>void;onend:()=>void;onerror:()=>void;start:()=>void}}; if(!w.webkitSpeechRecognition){setListening(true);setTimeout(()=>{setAnswer(sampleAnswers[question]);setListening(false)},900);return;} const rec=new w.webkitSpeechRecognition(); rec.lang="ko-KR"; rec.interimResults=false; rec.onresult=e=>setAnswer(e.results[0][0].transcript); rec.onend=()=>setListening(false); rec.onerror=()=>{setListening(false);setAnswer(sampleAnswers[question])}; setListening(true);rec.start(); };
  const previous:Record<DamageStage,DamageStage>={safety:"safety",capture:"safety",review:"capture",callStart:"review",call:"callStart",summary:"call",structure:"summary",support:"structure",documents:"support"};
  const header=<header className="record-header"><button onClick={stage==="safety"?onHome:()=>setStage(previous[stage])}>← 이전</button><Logo onHome={onHome}/><button onClick={onHome}>저장하고 나가기</button></header>;
  if(stage==="safety")return <main className="record-shell">{header}<section className="safety-screen"><div className="safety-visual"><span>!</span></div><p className="step-label">축산 피해 기록 전 꼭 확인해 주세요</p><h1>사람과 가축의 안전이<br/>가장 중요합니다</h1><p className="large-copy">안전한 곳에서만 촬영해 주세요.<br/><b>침수되거나 무너질 위험이 있는 축사에는 들어가지 마세요.</b></p><div className="safety-list"><p>✓ 침수된 축사의 전기시설에서 멀리 떨어지기</p><p>✓ 부상하거나 흥분한 가축 가까이 가지 않기</p><p>✓ 폐사축에 직접 접촉하거나 임의로 이동하지 않기</p><p>✓ 붕괴 위험이나 전염병 의심 시 담당기관에 먼저 연락하기</p></div><button className="primary wide" onClick={()=>setStage("capture")}>안전한 곳에 있습니다</button><button className="secondary wide" onClick={()=>alert("가족에게 도움 요청 문자를 보냈습니다. (데모)")}>가족에게 도움 요청</button></section></main>;
  if(stage==="capture")return <main className="record-shell">{header}<section className="capture-screen"><p className="step-label">1단계 · 축산 피해 사진</p><h1>가축과 축사 피해를<br/>사진으로 남겨주세요</h1><p className="large-copy">위험한 곳에 접근하지 말고 안전한 거리에서 여러 방향으로 촬영해 주세요.</p><div className="capture-box"><div className="camera-big">▣</div><b>축사 전체가 보이도록 찍어주세요</b><p>피해 가축 · 침수 높이 · 파손 시설 · 농장 표식</p><button className="primary" onClick={()=>cameraRef.current?.click()}>사진 찍기</button><button className="secondary" onClick={()=>fileRef.current?.click()}>휴대전화 사진에서 선택</button><button className="skip-photo" onClick={()=>setStage("review")}>사진 없이 데모 계속하기</button><input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" multiple onChange={addPhotos}/><input ref={fileRef} hidden type="file" accept="image/*" multiple onChange={addPhotos}/></div><aside className="photo-tips"><b>이렇게 찍으면 좋아요</b><span>① 축사 전체와 침수 높이</span><span>② 피해 가축은 안전한 거리에서</span><span>③ 벽·지붕·전기·급수시설</span><span>④ 사료 저장시설과 농장 표식</span></aside></section></main>;
  if(stage==="review")return <main className="record-shell">{header}<section className="review-screen"><div className="record-title"><div><p className="step-label">2단계 · 사진 확인</p><h1>등록한 사진을 확인해 주세요</h1><p>사진마다 설명을 덧붙일 수 있어요.</p></div><b>{photos.length}장 등록</b></div>{photos.length?<div className="photo-grid">{photos.map((p,i)=><article key={p.id}><img src={p.url} alt={`피해 현장 ${i+1}`}/><div><b>사진 {i+1}</b><small>{p.time} · {farm.location||"청주시 상당구 미원면"}</small><input value={p.note} onChange={e=>setPhotos(photos.map(x=>x.id===p.id?{...x,note:e.target.value}:x))} placeholder="사진 설명을 적어주세요"/><button onClick={()=>setPhotos(photos.filter(x=>x.id!==p.id))}>삭제</button></div></article>)}</div>:<div className="empty-photo"><b>등록된 사진이 없습니다</b><p>사진을 추가하거나 데모 사진 없이 계속할 수 있어요.</p></div>}<div className="review-actions"><button className="secondary" onClick={()=>fileRef.current?.click()}>＋ 다음 사진 추가</button><button className="primary" onClick={()=>setStage("callStart")}>촬영을 마쳤어요</button><input ref={fileRef} hidden type="file" accept="image/*" multiple onChange={addPhotos}/></div></section></main>;
  if(stage==="callStart")return <main className="record-shell call-bg">{header}<section className="call-start"><div className="ai-orb"><span>온</span><i></i><i></i></div><p className="call-status">농가온 AI가 기다리고 있어요</p><h1>축산 피해 사진을 확인했습니다.<br/>이제 편하게 말씀해 주세요.</h1><p>가축이나 축사에 어떤 피해가 있었는지 평소 말하듯 설명해 주세요.<br/>폐사·부상 마릿수 등 필요한 내용만 천천히 여쭤볼게요.</p><button className="call-button" onClick={beginCall}><span>●</span><b>말하기 시작</b></button><button className="help-input" onClick={beginCall}>⌨ 도움받아 입력</button><div className="voice-guide">🔊 AI 질문은 느리고 또렷한 음성과 큰 글자로 함께 안내됩니다.</div></section></main>;
  if(stage==="call")return <main className="record-shell call-bg">{header}<section className="call-layout"><aside className="call-person"><div className={`ai-orb small ${listening?"listening":""}`}><span>{listening?"듣는 중":"온"}</span><i></i><i></i></div><b>{listening?"말씀을 듣고 있어요":"농가온 AI와 통화 중"}</b><small>천천히 말씀하셔도 괜찮아요</small><button onClick={()=>speak(questions[question])}>🔊 질문 다시 듣기</button><button className="end-call" onClick={()=>setStage("summary")}>통화 마치기</button></aside><section className="chat-panel"><div className="chat-head"><div><b>피해 상황 대화</b><small>질문 {question+1} / {questions.length}</small></div><span>● 연결됨</span></div><div className="chat-log" aria-live="polite">{messages.map((m,i)=><div key={i} className={`bubble ${m.who}`}><small>{m.who==="ai"?"농가온 AI":"나"}</small><p>{m.text}</p>{m.who==="ai"&&i===messages.length-1&&<button onClick={()=>speak(m.text)}>🔊 다시 듣기</button>}</div>)}</div><div className="unknown-options">{question===3&&["잘 모르겠어요","나중에 확인할게요","사진으로 확인해 주세요","가족에게 물어볼게요"].map(x=><button key={x} onClick={()=>send(x)}>{x}</button>)}</div><div className="speech-entry"><button className={`mic-button ${listening?"active":""}`} onClick={listen}>{listening?"■":"●"}<span>{listening?"듣고 있어요":"눌러서 말하기"}</span></button><div><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="말씀하신 내용이 여기에 표시됩니다"/><div><button onClick={()=>setAnswer(sampleAnswers[question])}>예시 답변 사용</button><button className="send" onClick={()=>send()}>답변 보내기 →</button></div></div></div></section></section></main>;
  if(stage==="summary")return <main className="record-shell">{header}<section className="summary-screen"><div className="complete-mark">✓</div><p className="step-label">대화가 완료되었습니다</p><h1>말씀하신 축산 피해를<br/>이렇게 정리했어요</h1><div className="summary-read"><div className="summary-speaker">온</div><p>“8월 16일 새벽 집중호우로 청주시 소재 <b>한우 농장의 축사 2동 중 1동이 침수</b>되었습니다. 한우 45두 중 사용자가 신고한 폐사 가축은 2두이며, 축사 벽체와 사료 저장시설 복구가 필요합니다.”</p><button onClick={()=>speak("8월 16일 새벽 집중호우로 청주시 소재 한우 농장의 축사 2동 중 1동이 침수되었습니다. 한우 45두 중 사용자가 신고한 폐사 가축은 2두이며, 축사 벽체와 사료 저장시설 복구가 필요합니다.")}>🔊 천천히 다시 듣기</button></div><div className="summary-facts"><div><span>발생 시점</span><b>2026년 8월 16일 새벽 3시경</b></div><div><span>발생 위치</span><b>{farm.location||"청주시 상당구 미원면"}</b></div><div><span>가축 피해</span><b>{farm.livestockType||"한우"} 45두 중 폐사 신고 2두</b></div><div><span>시설 피해</span><b>축사 1동 침수 · 벽체 및 사료 저장시설 파손</b></div></div><p className="ai-notice">폐사 수와 시설 피해는 사용자 진술을 정리한 내용입니다. 공식 피해규모·지원 자격·보험금은 기관 확인이 필요합니다.</p><div className="summary-actions"><button className="secondary" onClick={()=>setStage("call")}>틀린 부분 고치기</button><button className="secondary" onClick={()=>{setQuestion(4);setStage("call")}}>추가로 말하기</button><button className="primary" onClick={()=>setStage("structure")}>내용이 맞아요</button></div></section></main>;
  if(stage==="structure")return <StructuredDamage farm={farm} header={header} onNext={()=>setStage("support")}/>;
  if(stage==="support")return <SupportPrograms header={header} onNext={()=>setStage("documents")}/>;
  return <Documents header={header} onHome={onHome}/>;
}

function StructuredDamage({farm,header,onNext}:{farm:Farm;header:ReactNode;onNext:()=>void}) { const rows=[
  ["발생일시","2026년 8월 16일 새벽 3시경","사용자 확인"],["재해 유형","집중호우 · 침수","사용자 확인"],["축종·평상시 사육","한우 · 45두","농장정보"],["신고 폐사 수","2두","사용자 확인"],["피해 축사","전체 2동 중 1동 침수","사용자 확인"],["피해 시설","축사 벽체 · 사료 저장시설","추가 확인 필요"],["공식 피해규모","아직 확인되지 않음","기관 확인 필요"]
]; return <main className="record-shell">{header}<section className="result-screen"><p className="step-label">AI 피해정보 구조화</p><h1>축산 피해정보를<br/>항목별로 정리했습니다</h1><p className="result-lead">농장정보, 사진 메타데이터, 음성 진술을 결합한 결과입니다.</p><div className="source-chips"><span>A 자동입력</span><span>B 사용자 확인</span><span>C 기관 확인</span></div><div className="structured-table">{rows.map(([a,b,c])=><div key={a}><span>{a}</span><b>{b}</b><em className={c.includes("기관")?"agency":c.includes("추가")?"check":"auto"}>{c}</em></div>)}</div><p className="ai-notice">AI는 공식 피해율, 손해액, 지원금 지급 여부를 확정하지 않습니다.</p><button className="primary result-next" onClick={onNext}>관련 복구지원 확인하기 →</button></section></main> }

function SupportPrograms({header,onNext}:{header:ReactNode;onNext:()=>void}) { const programs=[
  {status:"우선 확인",title:"자연재난 축산 피해 신고",why:"집중호우로 가축 폐사와 축사 침수 피해가 발생한 것으로 신고되었습니다.",org:"농장 소재지 읍·면·동 행정복지센터",docs:"피해 사진 · 농장정보 · 가축 피해현황",badge:"적용 가능성 있음"},
  {status:"함께 확인",title:"축사·축산시설 복구지원",why:"축사 벽체와 사료 저장시설 파손이 사용자 진술에 포함되어 있습니다.",org:"청주시 축산과",docs:"시설 피해사진 · 소유/임차 증빙 · 견적서",badge:"추가 확인 필요"},
  {status:"보험 접수",title:"가축재해보험 사고접수",why:"가축재해보험 가입정보가 등록되어 있으며 폐사 신고 2두가 있습니다.",org:"NH농협손해보험",docs:"보험 계약정보 · 피해 가축 사진 · 사고 경위",badge:"보험사 확인 필요"}
]; return <main className="record-shell">{header}<section className="result-screen"><p className="step-label">축산 피해복구 지원 탐색</p><h1>지금 확인할 지원 경로가<br/>3건 있습니다</h1><p className="result-lead">아래 내용은 데모용 안내입니다. 실제 신청기간과 자격은 담당기관 공고를 확인해야 합니다.</p><div className="program-list">{programs.map(p=><article key={p.title}><div><span>{p.status}</span><em>{p.badge}</em></div><h2>{p.title}</h2><p><b>관련 이유</b>{p.why}</p><p><b>담당기관</b>{p.org}</p><p><b>준비자료</b>{p.docs}</p><button>상세 조건 보기</button></article>)}</div><button className="primary result-next" onClick={onNext}>증빙과 문서 준비하기 →</button></section></main> }

function Documents({header,onHome}:{header:ReactNode;onHome:()=>void}) { const [tab,setTab]=useState("신고"); return <main className="record-shell">{header}<section className="result-screen"><p className="step-label">증빙 및 문서 자동화</p><h1>신고와 신청에 필요한 내용을<br/>초안으로 준비했습니다</h1><div className="document-layout"><aside><h2>준비 현황</h2>{["피해 현장 사진 3장","농장 기본정보","가축 피해현황","축사 시설 피해","가축재해보험 정보"].map((x,i)=><p key={x}><span>{i<3?"✓":"!"}</span>{x}<small>{i<3?"준비됨":"확인 필요"}</small></p>)}</aside><section><div className="doc-tabs">{["신고","피해현황","복구계획","보험접수"].map(x=><button className={tab===x?"active":""} key={x} onClick={()=>setTab(x)}>{x}</button>)}</div><div className="document-paper"><div className="paper-head"><span>문서 초안</span><b>{tab==="신고"?"자연재난 피해신고 내용":tab==="피해현황"?"축산 피해현황 요약":tab==="복구계획"?"축사 복구계획":"가축재해보험 사고접수 정보"}</b></div><p><mark>A 자동입력</mark> 대표자 김한우 / 미원한우농장 / 한우 45두 / 축사 2동</p><p><mark className="confirm">B 사용자 확인</mark> 2026년 8월 16일 새벽 집중호우로 축사 1동이 침수되었으며, 한우 2두가 폐사한 것으로 신고합니다.</p><p><mark className="confirm">B 사용자 확인</mark> 축사 벽체와 사료 저장시설이 파손되어 배수, 폐사축 처리 안내 및 시설 복구가 필요합니다.</p><p><mark className="agency-mark">C 기관 확인</mark> 공식 인정 폐사 수, 피해율, 손해액 및 지원 대상 여부는 현장 확인 후 결정됩니다.</p></div><div className="doc-buttons"><button className="secondary">내용 수정</button><button className="secondary" onClick={()=>window.print()}>인쇄·PDF 저장</button></div></section></div><p className="ai-notice">이 문서는 사용자가 검토할 수 있는 초안입니다. 제출 전 공식 서식과 담당기관 확인이 필요합니다.</p><button className="primary result-next" onClick={onHome}>홈으로 돌아가기</button></section></main> }

function MyPage({farm,draft,editing,setEditing,setDraft,onSave,onHome}:{farm:Farm;draft:Farm;editing:boolean;setEditing:(v:boolean)=>void;setDraft:(v:Farm)=>void;onSave:()=>void;onHome:()=>void}) { const groups:{title:string;fields:[keyof Farm,string][]}[]=[{title:"대표자 정보",fields:[["name","대표자명"],["phone","연락처"],["region","거주 주소"]]},{title:"축산농장 정보",fields:[["farmName","농장명"],["location","농장 주소"],["livestockType","축종"],["normalCount","평상시 사육두수"],["barnCount","축사 수"],["barnArea","축사 규모"],["ownership","소유·임차"],["permitNumber","허가·등록번호"],["businessRegistered","농업경영체 등록"]]},{title:"가축재해보험",fields:[["insuranceEnrolled","가입 여부"],["insurer","보험사"],["contractNumber","계약번호"]]}]; return <main className="app-shell"><header className="app-header"><Logo onHome={onHome}/><button className="text-button" onClick={onHome}>홈으로</button></header><section className="mypage"><div className="page-heading"><div><p className="eyebrow">내 축산농장</p><h1>축산농가 정보 관리</h1><p>피해신고, 복구지원, 보험접수에 반복해서 사용하는 정보예요.</p></div>{!editing&&<button className="secondary" onClick={()=>setEditing(true)}>정보 수정하기</button>}</div><article className="profile-summary"><div className="avatar">牛</div><div><h2>{farm.farmName||"미원한우농장"}</h2><p>{farm.livestockType||"한우"} {farm.normalCount||"45두"} · 축사 {farm.barnCount||"2동"}</p></div><span className="status">✓ 축산농가 등록 완료</span></article>{groups.map(g=><section className="info-card profile-group" key={g.title}><div className="info-title"><h2>{g.title}</h2><span>마지막 수정: 오늘</span></div><div className="info-grid">{g.fields.map(([key,label])=><label key={key}><span>{label}</span>{editing?<input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/>:<b>{farm[key]||"입력되지 않음"}</b>}</label>)}</div></section>)}{editing&&<div className="edit-actions profile-save"><button className="secondary" onClick={()=>setEditing(false)}>취소</button><button className="primary" onClick={onSave}>저장하기</button></div>}<button className="logout" onClick={onHome}>로그아웃</button></section><BottomNav onMyPage={()=>{}}/></main>; }
